site_name: Fitting Data
nav:
  - Introduction: index.md
  - Setup: 01_setup.md
  - Experiment: 02_experiment_details.md
  - Initial Plotting: 03_isolating_peaks.md
  - First fits: 04_fitting_curves.md
  - Line Fit: 05_linregress.md
  - Chi Squared: 06_chi_squared.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js