site_name: Fitting Data
nav:
  - Home: index.md
  - Introduction: 01_introduction.md
  - Setup: 02_setup.md
  - Experiment: 03_experiment_details.md
  - Initial Plotting: 04_isolating_peaks.md
  - First fits: 05_fitting_curves.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js